<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net6.0;netstandard2.0;net461;net481</TargetFrameworks>
    <RootNamespace>Standard.Licensing</RootNamespace>
    <AssemblyName>Standard.Licensing</AssemblyName>
    <Authors>Junian Triajianto; Stefan K.S. Tucker</Authors>
    <NeutralLanguage>en</NeutralLanguage>
    <Owners>junian; 12noon LLC</Owners>
    <PackageProjectUrl>https://www.junian.dev/Standard.Licensing/</PackageProjectUrl>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../../ReleaseNotes.txt"))</PackageReleaseNotes>
    <Summary>Easy-to-use licensing library for .NET and .NET Framework products.</Summary>
    <PackageTags>portable,licensing,key</PackageTags>
    <Title>Standard.Licensing</Title>
    <Description>Easy-to-use licensing library for .NET and .NET Framework products.</Description>
    <PackageId>Standard.Licensing</PackageId>
    <Copyright>Copyright (c) 2018 - 2026</Copyright>
    <RepositoryUrl>https://github.com/junian/Standard.Licensing</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Standard.Licensing.snk</AssemblyOriginatorKeyFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageIcon>standard-licensing-logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <CLSCompliant>True</CLSCompliant>
	
    <!-- Versions -->
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <ReleaseVersion>$(AssemblyVersion)</ReleaseVersion>
    <Version>$(AssemblyVersion)</Version>
    <FileVersion>$(AssemblyVersion)</FileVersion>
  </PropertyGroup>
	
  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
    <None Include="..\..\docs\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\assets\img\standard-licensing-logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
  </ItemGroup>
    
</Project>
